### ISSUE TITLE
性能原因

### ISSUE THREAD

**Issue by AAAAAA128** [hermosayhl/DeepUPE_pytorch#1]
我猜测作者能达到30db的性能和他使用了额外的数据有关系，就是论文里他收集的那个数据集，但是作者没有release。

**Comment by hermosayhl** [comment]
我认为不是额外的数据造成的。那个收集的数据集才 3000 对，我目前都没见到影。论文里那个 30，官方源码里测试 PSNR 的代码是错的，虚高了很多，作者是三通道分开算 PSNR，然后三通道取平均，但一般的算 PSNR 都是三通道一起算，从概率的角度，三个通道出现误差的概率要比一个通道出现误差的概率大，所以，他们那个实际性能也就 23.5 左右。

目前2020和2021的顶会顶刊论文，只要引用了这篇论文的，实验比较的结果都是 22-23 左右。总不可能大家都错吧。

**Comment by hermosayhl** [comment]
> 我猜测作者能达到30db的性能和他使用了额外的数据有关系，就是论文里他收集的那个数据集，但是作者没有release。

我认为不是额外的数据造成的。那个收集的数据集才 3000 对，我目前都没见到影。论文里那个 30，官方源码里测试 PSNR 的代码是错的，虚高了很多，作者是三通道分开算 PSNR，然后三通道取平均，但一般的算 PSNR 都是三通道一起算，从概率的角度，三个通道出现误差的概率要比一个通道出现误差的概率大，所以，他们那个实际性能也就 23.5 左右。

目前2020和2021的顶会顶刊论文，只要引用了这篇论文的，实验比较的结果都是 22-23 左右。总不可能大家都错吧。
