### ISSUE TITLE
你好，请问FiveK数据集除了格式从dng转换到jpg，还做了什么处理呢？官网下载下来的input图片比论文中贴出来的图片亮一些，是否调整过亮度呢？

### ISSUE THREAD

**Issue by LiveAndLearn322** [hermosayhl/DeepUPE_pytorch#4]

**Comment by hermosayhl** [comment]
我使用的 lightroom 导出的 png 格式，8 bit，默认 default(在左下角可以选择)

**Comment by LiveAndLearn322** [comment]
非常感谢你的回复。我尝试按照这个导出设置，导出的图片和论文中Input亮度不一样。请问能发一下更具体的操作吗？万分感谢！发自我的华为手机-------- 原始邮件 --------发件人： 北邮智科 16 级 大作业账号 ***@***.***>日期： 2022年3月19日周六 晚上9:48收件人： hermosayhl/DeepUPE_pytorch ***@***.***>抄送： LiveAndLearn322 ***@***.***>, Author ***@***.***>主    题： Re: [hermosayhl/DeepUPE_pytorch] 你好，请问FiveK数据集除了格式从dng转换到jpg，还做了什么处理呢？官网下载下来的input图片比论文中贴出来的图片亮一些，是否调整过亮度呢？ (Issue #4)

我使用的 lightroom 导出的 png 格式，8 bit，默认 default(在左下角可以选择)

**Comment by Varato** [comment]
因为这里的训练集输入是被压缩到 8bit JPG 图像了，相比 FiveK 原图 DNG 16bit 会丢失不少信息。同时，LightRoom 在导出 JPG 的时候也会加一个 gamma 映射使得图像变亮一些。

如果训练时能用 rawpy (pip install rawpy) 读取 16bit DNG 再转float, 可以保留更多暗像素细节，可能让该模型效果更好。

**Comment by McFly-Jia** [comment]
> 

我看您数据集中给出的格式是JPG格式的，是导出PNG格式后又转成JPG格式吗

**Comment by Maozhiquan** [comment]
> 因为这里的训练集输入是被压缩到 8bit JPG 图像了，相比 FiveK 原图 DNG 16bit 会丢失不少信息。同时，LightRoom 在导出 JPG 的时候也会加一个 gamma 映射使得图像变亮一些。
> 
> 如果训练时能用 rawpy (pip install rawpy) 读取 16bit DNG 再转float, 可以保留更多暗像素细节，可能让该模型效果更好。

您好，请问使用Lightroom导出这种比较暗（比retinexformer中提供的fivek数据集暗，比官网导出暗）的图片时，是采用的sRGB模式还是proRGB模式呢，如果您能回复感激不尽！祝您科研事业生活顺利
