### ISSUE TITLE
训练和测试数据

### ISSUE THREAD

**Issue by Arusa1** [hermosayhl/DeepUPE_pytorch#5]
老哥你好！你提到“_最终在 [MIT-Adobe FiveK](https://data.csail.mit.edu/graphics/fivek/) 数据集上，512px 分辨率，4500 对图像做训练 train ，剩下 500 对做验证 valid，PSNR 达到了 23.547db，SSIM 达到了 0.8578。_”，我想问一下是前4500张做训练后500张做验证还是说random sample的？
多谢！

**Comment by hermosayhl** [comment]
我这里做的其实不对。
我是随机打乱数据列表，随机采样。
现在是 4000 训练，500 验证，最后 500 测试（测试集在训练期间不可见）。

**Comment by Arusa1** [comment]
好嘞 谢谢老哥！
